docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo $CI_DOCKERHUB_PASSWORD | docker login -u "$CI_DOCKERHUB_USER" --password-stdin $CI_DOCKERHUB_REGISTRY
  script:
    - docker build --pull -t "index.docker.io/tbcp/nativemobile:latest" .
    - docker push "index.docker.io/tbcp/nativemobile:latest"
  only:
    - main
